### ISSUE TITLE
bitcoin-core rpc port fails with the default docker network

### ISSUE THREAD

**Issue by orlin** [SatoshiPortal/dockers#18]
Here is a report on some difficulties I experienced with setting up the `bitcoin-core` of this dockers repository.  I am running a brand new Ubuntu 19.04 with the [latest docker-ce installed with this script](https://github.com/orlin/dots/blob/master/install/linux-docker).  I have also put together [a script for setting up bitcoin-core](https://github.com/orlin/dots/blob/master/install/docker/bitcoin) based on your instructions.  I changed `bitcoin.conf` with `server=1` and `testnet=0` and kept the defaults for `rpcallowip=127.0.0.1` and `rpcport=8332`.  

At first glance everything works great, `bitcoind` syncs and I can conveniently [run `bitcoin-cli` with the help of some aliases](https://github.com/orlin/dots/blob/master/use/aliases/docker.sh).  The issue is that although the ports appear exposed for localhost use I cannot issue direct rpc requests without going through the docker command as setup with the `alias bitcoin-cli='docker exec -it btcnode bitcoin-cli -datadir=/.bitcoin'`. 

Here is an example command that should run but doesn't: `curl --user ${BTC_RPC_USER}:${BTC_RPC_PASS} --data-binary '{"jsonrpc":"1.0", "method":"getnetworkinfo", "params":[]}' -H 'content-type: text/plain;' http://127.0.0.1:8332/`.  The response I get from it is: `curl: (56) Recv failure: Connection reset by peer`.  I have the the rpc username and password correctly setup with the `rpcauth` option and the help of `curl -sSL https://raw.githubusercontent.com/bitcoin/bitcoin/master/share/rpcauth/rpcauth.py | python - rpcuser` though I also tried plain text `rpcuser` & `rpspassword`.

The point is that the command actually works as it should when running the container using docker's `host` network driver.  Another interesting observation is that the container gets removed from the bridge network after the first "Connection reset by peer" - disappearing from `docker network inspect bridge` or other commands such as `docker inspect -f "{{ .NetworkSettings.Networks.bridge.IPAddress }}" btcnode`.  It can be re-added with `docker network connect bridge btcnode` only do disappear again after issuing another curl rpc request at the 8332 port.  I have tried all kinds `bitcoin.conf` settings and none have made any difference.

Since you don't use the `--network host` in your `docker run` example I wonder if you experience the same rpc failure when using the default docker network bridge.  Having the bitcoin-core rpc (and other ports) work correctly is essential for all the other servers and tools that would depend on bitcoind.

**Comment by Kexkey** [comment]
Hi @orlin !

Since Bitcoin Core 0.18, you need a new confg in bitcoin.conf to be able to connect to the RPC port.  `rpcbind`.  I need to adjust the documentation.

testnet example:
```
testnet=1
rpcallowip=0.0.0.0/0
test.rpcbind=0.0.0.0
```

mainnet example:
```
rpcallowip=0.0.0.0/0
main.rpcbind=0.0.0.0
```

Note that this will bind to any interface, which is not secure.  If you are sure about the IP/hostname you'll use in your client, use it.

Let me know if that helps!

**Comment by orlin** [comment]
Thank you @Kexkey - this worked!  The `main.rpcbind` is what fixed it.

What would be a valid test command to run against the other 2 ports and are there any configuration tricks for those?  Would there be interest to add a shell script to this repo that tests the ports?  Especially the ZMQ port which I would need for [Samourai Dojo](https://github.com/Samourai-Wallet/samourai-dojo/blob/develop/doc/DOCKER_advanced_setups.md).

As I understand it: `0.0.0.0` opens the node to connections from anywhere.  How would you restrict it to localhost?  I tried `127.0.0.1` and that didn't work.  Another question would be how to restrict it to several IPs?  I'm thinking localhost + Dojo though for sure also other bitcoin related containers...  I've only seen multiple config entries being used for `rpcallowip`.  Which are the ports that would be important to protect - just `8332`?

**Comment by Kexkey** [comment]
Hi @orlin 

`0.0.0.0` as the bind address means that the client can use any name/IP when calling Bitcoin Core.  For example, if you have `127.0.0.1` as the bind address, the client must use `127.0.0.1:18332` when calling RPC.

`rpcallowip` will allow queries to only come from the supplied IPs.  You can have that config multiple times in bitcoin.conf.

RPC port is the most important to protect, indeed.

Bitcoin Core's docs explain it better than I.  Same goes for ZMQ.  You need to tell Core to publish on specific IPs/ports.  You need a ZMQ client that will listen to those IPs/ports.

hth
