### ISSUE TITLE
Hyperlinks in List of DockerFiles are all 404'ing

### ISSUE THREAD

**Issue by GlenCooper** [SatoshiPortal/dockers#20]
Every link in https://github.com/SatoshiPortal/dockers#list-of-dockerfiles is 404'ing...

![Screenshot from 2020-01-24 19-42-09](https://user-images.githubusercontent.com/967793/73098797-07a4e700-3ee2-11ea-9fce-f9f50ee5eb20.png)
![Screenshot from 2020-01-24 19-43-30](https://user-images.githubusercontent.com/967793/73098802-0a074100-3ee2-11ea-9ace-cc5b9b6a28e4.png)

Can someone who knows what's broken here please fix?  Thanks

**Comment by Kexkey** [comment]
Thanks, it's now fixed!
